export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';

export const FACEBOOK_LOGIN_LOADING = 'FACEBOOK_LOGIN_LOADING';
export const FACEBOOK_LOGIN_READY = 'FACEBOOK_LOGIN_READY';
export const FACEBOOK_LOGIN_FAILURE = 'FACEBOOK_LOGIN_FAILURE';

export const GOOGLE_LOGIN_LOADING = 'GOOGLE_LOGIN_LOADING';
export const GOOGLE_LOGIN_READY = 'GOOGLE_LOGIN_READY';
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE';

export const REQUEST_PASSWORD_CHANGE_SUCCESS = 'REQUEST_PASSWORD_CHANGE_SUCCESS';
export const REQUEST_PASSWORD_CHANGE_FAILURE = 'REQUEST_PASSWORD_CHANGE_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const USER_LOADING = 'USER_LOADING';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const MESSAGER_SET_VALUE = 'MESSAGER_SET_VALUE';

export const SET_LANGUAGE = 'SET_LANGUAGE';
