{
 "title": "Dashboard Template",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster CPU, Memory & Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Average Cluster CPU usage",
   "type": "gauge",
   "description": "Show Average CPU usage in 5 minutes interval",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])))"
    }
   ]
  },
  {
   "title": "Cluster Memory usage (%)",
   "type": "gauge",
   "description": "How many percentage of total memory is in use",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_Active_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Cluster disk usage (%)",
   "type": "gauge",
   "description": "Percentage of disk space use",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_avail_bytes) / sum(node_filesystem_size_bytes))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "description": "Number of CPUs in available",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "CPUs" }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "stat",
   "description": "Number of CPUs in use",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores) - (sum(rate(container_cpu_usage_seconds_total[2m])))"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "description": "Total memory available",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "description": "How much memory is used currently",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(node_memory_Active_bytes)" }
   ]
  },
  {
   "title": "Disk space total",
   "type": "stat",
   "description": "Total available disk space",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "stat",
   "description": "Total disk space used",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes - node_filesystem_avail_bytes)"
    }
   ]
  },
  {
   "title": "CPU usage per CPU (%)",
   "type": "graph",
   "description": "Average CPU percentage per CPU in 5 minute interval",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory usage  (%) Graph",
   "type": "graph",
   "description": "Memory usage over time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_Active_bytes / on (instance) node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Disk usage (%) Graph",
   "type": "graph",
   "description": "Disk space usage over time",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ( avg(node_filesystem_avail_bytes / node_filesystem_size_bytes))"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Network (Receive/Transmit)",
   "type": "graph",
   "description": "Network I/O pressure with received kbs and transmitted kbs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total[1m]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}