---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.objects.names.dbSecretName | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ required "A valid .Values.global.persistence.db.name entry required!" .Values.global.persistence.db.name | b64enc | quote }}
  POSTGRES_USER: {{ required "A valid .Values.global.persistence.db.username entry required!" .Values.global.persistence.db.username | b64enc | quote }}
  {{ $secret := lookup "v1" "Secret" .Release.Namespace (.Values.global.objects.names.dbSecretName) -}}
  {{- $pass := ""}}
  {{ if $secret -}}
  {{- $pass = ($secret.data.POSTGRES_PASSWORD | b64dec) -}}
  POSTGRES_PASSWORD: {{ $pass | b64enc | quote }}
  {{ else -}}
  {{- $pass = randAlphaNum 24 -}}
  POSTGRES_PASSWORD: {{ $pass | b64enc | quote }}
  {{ end -}}
  DATABASE_URL: {{ (printf "postgres://%s:%s@%s-database:5432/%s" .Values.global.persistence.db.username $pass .Release.Name .Values.global.persistence.db.name) | b64enc | quote }}